---
title: "shiny_demo"
author: "David Chiu"
date: "2016年3月24日"
output: html_document
---
```{r, include=TRUE, warning=FALSE, echo=FALSE}
#install.packages("rvest")
library(rvest)
```

# 抓取網頁原始碼
```{r}
newsurl <- "http://www.appledaily.com.tw/realtimenews/section/new/"
apple <- read_html(newsurl, encoding="UTF-8")


```

# 抽取列表資訊
```{r}
apple %>% html_nodes('li.rtddt') %>% iconv(from='UTF-8', to='UTF-8') 

rtddt <- apple %>% html_nodes('.rtddt')  
time <- rtddt %>% html_nodes('time') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
title <- rtddt %>% html_nodes('h1') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')
category <- rtddt %>% html_nodes('h2') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8')

applenews <- data.frame(time =time, title= title, category = category)



```
# 增加網路連結
```{r}
domain <- 'http://www.appledaily.com.tw'

url <- rtddt %>% html_nodes('a') %>% html_attr('href')
url <- gsub(domain, "", url)
url <- paste0(domain, url)
applenews <- data.frame(time =time, title= title, category = category, url = url)
```

# 取得內容
```{r}
applenews$url <- as.character(applenews$url)
applenews$content <- sapply(applenews$url, function(e){read_html(e) %>% html_nodes('.articulum.trans') %>% html_text() %>% iconv(from='UTF-8', to='UTF-8') } )
```